build-dla:
    # Run build command first to observe possible errors
    cargo build --target=riscv64imac-unknown-none-elf --release --lib
    # Rub objcopy (on the incremental outputs of cargo build)
    cargo objcopy --target=riscv64imac-unknown-none-elf --release --lib -- --weaken

build-dla-debug:
    # Run build command first to observe possible errors
    cargo build --target=riscv64imac-unknown-none-elf --lib
    # Rub objcopy (on the incremental outputs of cargo build)
    cargo objcopy --target=riscv64imac-unknown-none-elf --lib -- --weaken
