[target.riscv64imac-unknown-none-elf]
runner = "../../scripts/run_on_hpc.sh"

[target.riscv32imc-unknown-none-elf]
runner = "../../scripts/run_on_sysctrl.sh"
rustflags = ["-C", "link-arg=-Tmem_sysctrl.x", "-C", "link-arg=-Tlink.x"]
