name: Test memory maps

on:
  schedule:
    - cron: "14 3 * * 5" # every friday at 03:14
  workflow_dispatch: # Allow manual dispatch

env:
  CI: 1
  CARGO_TERM_COLOR: always
  RENODE_DIR: /opt/renode/
  # Used by renode-test to generate snapshots of failed tests
  RENODE_CI_MODE: YES
  BIN: test-memory-maps

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        device: [
          C2C_config, C2C_serial, DLA, DMA0, DMA1, DSP, EthSSPadConf, HPC, SYSCTRL,
          apb_gpio, apb_i2c, apb_pad_conf_reg_array, apb_spim0, apb_spim1, apb_sw_irq, apb_uart0, apb_uart1,
          mdio_map0, mdio_map1, sdram_cfg]
    steps:
    - uses: actions/checkout@v4
    - name: Install requirements
      run: rustup target add riscv64imac-unknown-none-elf
    - name: Build test
      working-directory: ./examples/hpc/test-memory-maps
      run: |
        DEVICE=${{ matrix.device }} cargo build --release
        mv ../target/riscv64imac-unknown-none-elf/release/$BIN ${{ matrix.device }}.elf
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.device }}.elf
        path: ./examples/hpc/test-memory-maps/${{ matrix.device }}.elf
        if-no-files-found: error
        retention-days: 14

  run-test:
    needs: build-test

    runs-on: ubuntu-latest
    container:
      image: antmicro/renode:1.14.0
      options: --user root

    strategy:
      matrix:
        device: [
          C2C_config, C2C_serial, DLA, DMA0, DMA1, DSP, EthSSPadConf, HPC, SYSCTRL,
          apb_gpio, apb_i2c, apb_pad_conf_reg_array, apb_spim0, apb_spim1, apb_sw_irq, apb_uart0, apb_uart1,
          mdio_map0, mdio_map1, sdram_cfg]
    steps:
    - uses: actions/checkout@v4
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ matrix.device }}.elf
    - name: Create Renode peripheral symlinks
      run: ln -s $(readlink -f "./vp/devel/python_peripherals/DLA.py") "$RENODE_DIR/scripts/pydev/DLA.py"
    - name: Run test
      run: renode-test ./scripts/robot/test_pass.robot --variable BIN:"$(readlink -f ${{ matrix.device }}.elf)"
    - name: Upload snapshots
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        path: snapshots/
