name: Validate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CI: 1
  CARGO_TERM_COLOR: always
  RENODE_PATH: /opt/renode/
  # Used by renode-test to generate snapshots of failed tests
  RENODE_CI_MODE: YES

jobs:
  build-dla-example:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install requirements
      run: rustup target add riscv64imac-unknown-none-elf
    - name: Build examples
      working-directory: ./examples/hpc/hello-dla
      run: cargo build --example dla
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dla-debug
        path: ./examples/hpc/hello-dla/target/riscv64imac-unknown-none-elf/debug/examples/dla
        if-no-files-found: error
        retention-days: 14

  run-dla-example:
    needs: build-dla-example

    runs-on: ubuntu-latest
    container:
      image: antmicro/renode:1.14.0
      options: --user root

    env:
      BIN: dla

    steps:
    - uses: actions/checkout@v4
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: dla-debug
    - name: Create Renode peripheral symlinks
      run: ln -s $(readlink -f "./vp/devel/python_peripherals/DLA.py") "$RENODE_PATH/scripts/pydev/DLA.py"
    - name: Run example
      run: renode-test scripts/robot/hello_dla.robot --variable BIN:"$(readlink -f $BIN)"
    - name: Upload snapshots
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        path: snapshots/
